console.log(typeof Array, typeof new Array, typeof [])

let aprovados = new Array('a', 'b', 'c')
console.log(aprovados)

aprovados.splice(1, 1, 'd', 'e')
console.log(aprovados)
aprovados.splice(1, 2)
console.log(aprovados)
aprovados.splice(1, 0, 'g', 'h')
console.log(aprovados)
aprovados.splice(9, 0, 'i', 'j')
console.log(aprovados)
aprovados.splice(15, 2, 'k', 'l')
console.log(aprovados)
console.log(aprovados.pop())
console.log(aprovados)
aprovados.push('m')
console.log(aprovados)
console.log(aprovados.shift())
console.log(aprovados)
aprovados.unshift('n')
console.log(aprovados)

const someones = aprovados.slice(5)
console.log(someones)

const anyones = aprovados.slice(2, 7)
console.log(anyones)
